const tests={
profile:{title:'Профильные дисциплины',questions:[
['Какой алгоритм применяют для поиска элемента в отсортированном массиве?',['Линейный поиск','Бинарный поиск','Поиск в глубину','Хеширование'],1],
['Как называется структура данных, работающая по принципу LIFO?',['Очередь','Стек','Дерево','Граф'],1],
['Первичный ключ в реляционной базе данных должен…',['содержать повторяющиеся значения','однозначно идентифицировать запись','хранить только числа','быть внешним ключом'],1],
['Какой SQL-оператор используется для извлечения данных?',['SELECT','UPDATE','INSERT','DELETE'],0],
['Что является основным назначением нормализации базы данных?',['Увеличить размер таблиц','Уменьшить избыточность данных','Зашифровать информацию','Удалить ключи'],1],
['К какому методу педагогического исследования относится анкетирование?',['Эмпирическому','Теоретическому','Математическому','Историческому'],0],
['Что в педагогике называют формативным оцениванием?',['Оценивание только в конце обучения','Оценивание для улучшения обучения','Выставление итоговой отметки','Распределение учеников по группам'],1],
['Как называется правило, по которому один элемент таблицы связан с одним или несколькими элементами другой?',['Связь между таблицами','Индексирование','Компиляция','Сортировка'],0],
['Какая сложность у бинарного поиска?',['O(n)','O(log n)','O(n²)','O(1)'],1],
['Какой компонент базы данных обеспечивает целостность связей?',['Внешний ключ','Текстовое поле','Представление','Отчёт'],0]]},
readiness:{title:'Готовность к обучению',questions:[
['Какой вывод логически следует: «Все магистранты изучают методологию. Айдана — магистрант»?',['Айдана изучает методологию','Айдана не изучает методологию','Методологию изучают только магистранты','Вывод сделать нельзя'],0],
['Какой вопрос помогает проверить аргумент?',['Кто это сказал?','Какие доказательства подтверждают утверждение?','Нравится ли вам идея?','Как быстро это произошло?'],1],
['Что является признаком критического мышления?',['Принятие первого ответа','Оценка доказательств и альтернатив','Запоминание без понимания','Отказ от вопросов'],1],
['Продолжите ряд: 3, 6, 12, 24, …',['27','36','48','54'],2],
['Если утверждение опирается на мнение одного человека, это…',['достаточное доказательство','авторитетный источник без проверки','основание, которое следует дополнительно проверить','логический закон'],2],
['Какой тип мышления нужен для сравнения нескольких вариантов решения?',['Аналитическое','Механическое','Случайное','Интуитивное без проверки'],0],
['Что точнее всего описывает «причинно-следственную связь»?',['События произошли одновременно','Одно явление влияет на возникновение другого','Два мнения совпали','Факт повторяется'],1],
['Найдите лишнее: тезис, аргумент, доказательство, настроение.',['Тезис','Аргумент','Доказательство','Настроение'],3],
['Как лучше поступить с противоречивой информацией?',['Выбрать более приятную версию','Сравнить источники и основания','Игнорировать оба источника','Сразу сделать вывод'],1],
['Что означает обобщение в рассуждении?',['Переход от частных фактов к общему выводу','Поиск ошибки в тексте','Запоминание определения','Пересказ источника'],0]]},
english:{title:'English language',questions:[
['Choose the correct option: My computer ___ be old, but it still works well.',['may','mustn’t','are','having'],0],
['Choose the correct sentence.',['Every teacher have to attend the seminar.','Every teacher has to attend the seminar.','Every teacher having attend the seminar.','Every teacher is attend the seminar.'],1],
['Complete the sentence: How is your sister now? Is she getting ___?',['good','better','best','well'],1],
['Choose the correct word: Did you buy ___ organic from the farmers’ market?',['anything','something','nothing','every'],0],
['What does the idiom “have a sweet tooth” mean?',['To dislike desserts','To like eating sweet foods','To visit a dentist','To cook a cake'],1],
['Choose the correct tense: She ___ her homework before she went out.',['finishes','has finished','had finished','was finish'],2],
['Choose the correct comparative: They work ___ than you.',['hard','harder','hardest','more hard'],1],
['Which is a linking word?',['Obviously','Table','Quickly','Student'],0],
['Complete the sentence: Can you ___? I can’t hear you.',['speak up','speak out','speak over','speak for'],0],
['Which sentence is in Present Simple?',['It is difficult to control sugar-eating habits.','It was difficult yesterday.','It has been difficult.','It will be difficult.'],0]]}
};
tests.profile.questions=[
['Какой оператор выводит данные в Python?',['print()','input()','len()','range()'],0],['Какой тип данных хранит целые числа в C++?',['int','float','char','bool'],0],['Что делает цикл for?',['Повторяет блок кода заданное число раз','Завершает программу','Создаёт класс','Удаляет переменную'],0],['Какой оператор проверяет равенство в Python?',['==','=','!=','>='],0],['Что хранит массив?',['Набор однотипных элементов','Только текст','Только одно число','Команду вывода'],0],['Какая структура работает по принципу LIFO?',['Стек','Очередь','Массив','Список'],0],['Какова сложность бинарного поиска?',['O(log n)','O(n²)','O(n)','O(1)'],0],['Что возвращает функция len() в Python?',['Количество элементов','Последний элемент','Тип переменной','Сумму чисел'],0],['Какой цикл выполняется, пока условие истинно?',['while','for','if','switch'],0],['Что означает O(1) в оценке сложности?',['Постоянное время','Линейное время','Квадратичное время','Логарифмическое время'],0],['Какой оператор добавляет элемент в конец списка Python?',['append()','pop()','sort()','clear()'],0],['Что такое рекурсия?',['Вызов функцией самой себя','Удаление функции','Объявление массива','Сортировка данных'],0],['Что в C++ обозначает символ //?',['Однострочный комментарий','Деление','Начало строки','Оператор сравнения'],0],['Какой оператор используется для ветвления?',['if','for','break','import'],0],['Что делает оператор break в цикле?',['Немедленно завершает цикл','Повторяет цикл','Пропускает все условия','Создаёт функцию'],0],['Какая структура данных использует принцип FIFO?',['Очередь','Стек','Дерево','Множество'],0],['Что такое переменная?',['Именованная область хранения значения','Команда вывода','Тип цикла','Ошибка программы'],0],['Какой метод сортирует список Python на месте?',['sort()','append()','len()','range()'],0],['Какова сложность двух вложенных циклов по n элементов?',['O(n²)','O(n)','O(log n)','O(1)'],0],['Что такое алгоритм?',['Последовательность шагов для решения задачи','Тип файла','Сетевая атака','База данных'],0],
['Что означает КЦД-триада в информационной безопасности?',['Конфиденциальность, целостность, доступность','Контроль, защита, данные','Код, запись, доступ','Ключ, цепь, домен'],0],['Какова цель конфиденциальности?',['Не допустить раскрытия данных неавторизованным лицам','Ускорить сеть','Удалить резервные копии','Сделать пароль короче'],0],['Что обеспечивает целостность данных?',['Защиту от несанкционированного изменения','Публичный доступ','Удаление шифрования','Увеличение объёма файла'],0],['Что означает доступность?',['Система и данные доступны уполномоченным пользователям','Данные открыты всем','Файлы удалены','Пароль отсутствует'],0],['Какой тип ПО требует выкуп за расшифровку файлов?',['Ransomware','Antivirus','Firewall','Compiler'],0],['Что такое фишинг?',['Обман для получения данных пользователя','Метод резервного копирования','Тип базы данных','Язык программирования'],0],['Как называется вредоносная программа, маскирующаяся под полезную?',['Троян','Брандмауэр','Сертификат','Патч'],0],['Какой инструмент фильтрует сетевой трафик?',['Межсетевой экран','Текстовый редактор','Архиватор','Компилятор'],0],['Что такое SQL-инъекция?',['Внедрение вредоносного SQL-кода через ввод','Шифрование базы данных','Резервное копирование','Обновление драйвера'],0],['Какой протокол защищает передачу данных в браузере?',['HTTPS','HTTP','FTP','Telnet'],0],['Какое шифрование использует один общий ключ?',['Симметричное','Асимметричное','Хеширование','Открытое'],0],['Что характерно для асимметричного шифрования?',['Используется пара открытого и закрытого ключей','Применяется один ключ','Нельзя передавать данные','Не требует алгоритма'],0],['Для чего используется хеш-функция?',['Проверка целостности данных','Расшифровка сообщений','Ускорение монитора','Создание вируса'],0],['Что такое многофакторная аутентификация?',['Проверка личности несколькими факторами','Один длинный пароль','Открытый доступ','Отключение учётной записи'],0],['Какой пароль наиболее устойчив?',['Длинная уникальная парольная фраза','12345678','Имя пользователя','Дата рождения'],0],['Что делает антивирус?',['Обнаруживает и нейтрализует вредоносное ПО','Шифрует все файлы','Создаёт пароли','Заменяет ОС'],0],['Что такое резервное копирование?',['Создание копий данных для восстановления','Удаление старых файлов','Передача пароля','Отключение сети'],0],['Какую атаку предотвращает регулярное обновление ПО?',['Использование известных уязвимостей','Утрату клавиатуры','Ошибку печати','Сжатие файлов'],0],['Что устанавливает стандарт ISO/IEC 27001?',['Требования к системе менеджмента ИБ','Правила языка Python','Формат электронных таблиц','Стандарт скорости сети'],0],['Что следует сделать при подозрении на фишинговое письмо?',['Не переходить по ссылкам и сообщить специалисту','Сразу открыть вложение','Отправить пароль','Переслать всем коллегам'],0]
];
tests.english.questions.push(
['Choose the best response: “Could you repeat that, please?”',['Of course.','I repeated yesterday.','No, I am repeat.','It repeats.'],0],['Choose the correct word: The lecture was ___, so I took notes.',['interesting','interest','interested','interestingly'],0],['Complete: Students ___ submit the form by Friday.',['must','must to','are must','musts'],0],['Choose the correct form: She ___ dinner when I called.',['was cooking','cooks','has cooked','will cook'],0],['Which word is closest in meaning to “essential”?',['necessary','optional','unusual','distant'],0],['Choose the correct word: We need ___ information before deciding.',['more','many','few','less'],0],['Complete: The results ___ tomorrow.',['will be announced','announce','are announce','will announced'],0],['Choose the correct preposition: He succeeded ___ solving the problem.',['in','at','on','with'],0],['Choose the correct form: I ___ this book already.',['have read','readed','am reading','will read'],0],['Choose the correct sentence.',['There is little time left.','There are little time left.','There is few time left.','There are few time left.'],0],['What does “academic” relate to?',['Education and study','Sports only','Weather','Cooking'],0],['Choose the correct word: The professor gave us useful ___.',['advice','advices','an advice','advises'],0],['Complete: If it ___ tomorrow, we will stay inside.',['rains','rained','will rain','raining'],0],['Choose the antonym of “complex”.',['simple','difficult','detailed','academic'],0],['Choose the correct form: They ___ the project by Monday.',['will have finished','finish','finished','are finish'],0],['Read: “The library is closed on Sundays, but its online catalogue is available every day.” What is available on Sundays?',['The online catalogue','The reading room','The librarian','Printed books only'],0],['Read: “Mira revised her notes before the exam and felt more confident.” Why did Mira feel confident?',['She revised her notes','The exam was cancelled','She changed her course','She missed the exam'],0],['Read: “The experiment was repeated three times to make the results more reliable.” Why was it repeated?',['To improve reliability','To make it shorter','To change the topic','To avoid recording data'],0],['Read: “Although the train was delayed, the meeting started on time online.” How did the meeting start on time?',['It was held online','The train arrived early','It was cancelled','Everyone travelled by car'],0],['Read: “Regular exercise can improve concentration and reduce stress.” Which benefit is mentioned?',['Better concentration','Higher ticket prices','Longer holidays','Faster internet'],0]
);
tests.profile.questions.push(
['Как называется обход дерева, при котором сначала посещается вершина, затем левое и правое поддеревья?',['Прямой','Симметричный','Обратный','Параллельный'],0],
['Какая структура данных используется для реализации очереди?',['FIFO','LIFO','LILO','FILO'],0],
['Какой SQL-оператор объединяет строки из двух таблиц по условию?',['JOIN','GROUP','ORDER','ALTER'],0],
['Какой вид ключа ссылается на первичный ключ другой таблицы?',['Внешний ключ','Составной ключ','Уникальный ключ','Индекс'],0],
['Что возвращает функция COUNT(*) в SQL?',['Количество строк','Сумму значений','Среднее значение','Первую запись'],0],
['Какая команда изменяет существующие записи в таблице?',['UPDATE','CREATE','SELECT','DROP'],0],
['Как называется алгоритм сортировки, который попарно сравнивает соседние элементы?',['Пузырьковая сортировка','Бинарный поиск','Обход графа','Хеширование'],0],
['Что такое рекурсия?',['Вызов функцией самой себя','Удаление функции','Создание таблицы','Сортировка данных'],0],
['Какой тип данных обычно хранит логическое значение?',['Boolean','String','Float','Date'],0],
['Что означает ACID в базах данных?',['Свойства транзакций','Типы индексов','Язык запросов','Метод сортировки'],0],
['Какова цель индексирования таблицы?',['Ускорить поиск данных','Удалить дубликаты','Заменить ключи','Увеличить размер файла'],0],
['Как называется оценивание, которое проводится после завершения темы?',['Суммативное','Формативное','Диагностическое','Взаимное'],0],
['Что является целью педагогического наблюдения?',['Сбор фактов об учебном процессе','Выставление оценки','Создание учебника','Замена эксперимента'],0],
['Какой метод обучения предполагает активное обсуждение вопроса учащимися?',['Дискуссия','Диктант','Инструктаж','Заучивание'],0],
['Что отражает учебная программа?',['Содержание и последовательность обучения','Только расписание','Финансы школы','Личные данные учеников'],0],
['Как называется связь между двумя таблицами, где одной записи первой соответствует много записей второй?',['Один-ко-многим','Один-к-одному','Многие-к-одному','Нулевая связь'],0],
['Какой оператор сортирует результат SQL-запроса?',['ORDER BY','WHERE','HAVING','VALUES'],0],
['Что обеспечивает первичный ключ?',['Уникальность записи','Дублирование записей','Шифрование таблицы','Удаление столбцов'],0],
['Что в алгоритмах называют сложностью O(1)?',['Постоянное время','Линейное время','Квадратичное время','Логарифмическое время'],0],
['Какой подход в обучении учитывает индивидуальные особенности ученика?',['Личностно-ориентированный','Фронтальный без различий','Случайный','Только репродуктивный'],0]
);
tests.readiness.questions.push(
['Как называется ошибка, когда частный случай выдают за общее правило?',['Поспешное обобщение','Дедукция','Сравнение','Классификация'],0],
['Какой источник надёжнее для научного утверждения?',['Рецензируемое исследование','Случайный комментарий','Рекламный текст','Неподписанное сообщение'],0],
['Если A больше B, а B больше C, то…',['A больше C','C больше A','A равно C','Вывод невозможен'],0],
['Какой элемент аргумента объясняет, почему доказательство поддерживает тезис?',['Обоснование','Пример','Заголовок','Эмоция'],0],
['Что нужно сделать перед выводом по диаграмме?',['Проверить подписи и масштаб','Выбрать яркий цвет','Сразу пересказать','Игнорировать источник'],0],
['Как называется рассуждение от общего правила к частному выводу?',['Дедукция','Индукция','Ассоциация','Аналогия'],0],
['В чём риск ложной дилеммы?',['Игнорируются другие возможные варианты','Слишком много фактов','Есть точная статистика','Аргумент доказан'],0],
['Какой приём помогает отделить факт от мнения?',['Проверить возможность доказательства','Согласиться с автором','Выбрать самый длинный текст','Повторить утверждение'],0],
['Продолжите ряд: 2, 5, 10, 17, …',['26','22','24','34'],0],
['Что такое контраргумент?',['Возражение против тезиса','Повтор тезиса','Название текста','Личный пример без связи'],0],
['Какая информация нужна для проверки статистики?',['Источник, выборка и период','Только цвет диаграммы','Имя читателя','Размер шрифта'],0],
['Что означает объективность в анализе?',['Опора на проверяемые данные','Отказ от фактов','Выбор удобного вывода','Следование настроению'],0],
['Какой вывод корректен: «Некоторые студенты изучают английский»?',['Нельзя утверждать, что все студенты изучают английский','Все студенты изучают английский','Никто не изучает английский','Английский не нужен'],0],
['Что лучше всего показывает причинность?',['Контролируемое исследование','Совпадение двух событий','Один пример','Личное впечатление'],0],
['Что следует сделать при обнаружении логического противоречия?',['Перепроверить посылки и вывод','Игнорировать его','Добавить эмоций','Сменить тему'],0],
['Как называется сравнение объектов по существенным признакам?',['Аналогия','Гипотеза','Репродукция','Догадка'],0],
['Какой вопрос выявляет скрытое допущение?',['На чём основано это утверждение?','Кто первым сказал?','Нравится ли идея?','Какой цвет у схемы?'],0],
['Если утверждение невозможно проверить, его следует…',['Считать гипотезой до проверки','Сразу признать фактом','Использовать как доказательство','Не читать'],0],
['Какой шаг завершает критический анализ текста?',['Обоснованный вывод','Первое впечатление','Копирование фразы','Выбор заголовка'],0],
['Что помогает избежать предвзятости?',['Рассмотреть альтернативные объяснения','Искать только подтверждения','Игнорировать несогласие','Доверять слухам'],0]
);
tests.english.questions.push(
['Choose the correct form: If I ___ more time, I would travel.',['had','have','will have','having'],0],
['Choose the correct article: She is ___ honest person.',['an','a','the','no article'],0],
['Complete the sentence: I have lived here ___ 2020.',['since','for','from','during'],0],
['Choose the synonym for “rapid”.',['quick','slow','weak','quiet'],0],
['Choose the correct passive voice: People speak English worldwide.',['English is spoken worldwide.','English speaks worldwide.','English was speak worldwide.','English speaking worldwide.'],0],
['Complete the sentence: There aren’t ___ chairs in the room.',['enough','too','much','very'],0],
['Which word is an adverb?',['carefully','careful','care','carefulness'],0],
['Choose the correct preposition: She is interested ___ science.',['in','on','at','for'],0],
['Complete the sentence: By next year, I ___ my degree.',['will have completed','complete','completed','am complete'],0],
['Choose the correct question tag: You study every day, ___?',['don’t you','do you','are you','will you'],0],
['What does “reliable” mean?',['Can be trusted','Very expensive','Hard to read','Easy to break'],0],
['Choose the correct word: I look forward to ___ from you.',['hearing','hear','heard','have heard'],0],
['Complete the sentence: Neither Anna nor her friends ___ late.',['are','is','was','be'],0],
['Choose the correct reported speech: He said, “I am tired.”',['He said that he was tired.','He said that I am tired.','He says he tired.','He said tired.'],0],
['Which word is a noun?',['knowledge','know','knowing','known'],0],
['Complete the sentence: This is the book ___ I told you about.',['that','where','who','when'],0],
['Choose the correct form: She ___ to London twice.',['has been','has gone','was going','goes'],0],
['What is the opposite of “increase”?',['decrease','develop','improve','expand'],0],
['Complete the sentence: I wish I ___ speak French fluently.',['could','can','will','should'],0],
['Choose the correct connector: ___ it was raining, we went for a walk.',['Although','Because','So','Therefore'],0]
);

tests.profile.questions=tests.profile.questions.slice(0,40);
tests.english.questions.splice(0,15,
['Maria is annoyed because people tend to…',['talk too much','complain and shout at her','be late for work','be too strict'],1],['Maria’s workplace is a…',['office','laboratory','cubicle','dormitory'],2],['Maria jumps when she hears the phone at home because she… all day.',['answers calls','sells mobiles','sits in a cubicle','shouts at customers'],0],['Maria’s company is located in…',['Milan','Michigan','Madrid','Manchester'],2],['Maria smokes too much and cannot sleep well because of…',['her husband’s job','street noise','neighbours’ pets','the phone'],3],['Maria deals with… during her working day.',['games','calls','talks','noise'],1],['Maria is not satisfied with her job, so she wants to…',['reduce','hire','fire','quit'],3],['Maria wants to disconnect the phone at…',['the boss’s room','her neighbour’s home','home','her workplace'],2],['Pat says it is great that she…',['works flexible hours','meets colleagues','does sports','travels seldom'],0],['According to the dialogue, Tim is really into…',['karate','cinema','music','jazz'],3],['Tim… meets his colleagues after work.',['usually','often','never','sometimes'],0],['The dialogue is mainly about…',['golf and cuisine','jobs and leisure','films and discos','pastime activities and classes'],1],['Pat’s work is connected with…',['sports','computers','the Internet','travelling'],2],['According to the dialogue, Pat is really into…',['restaurants','martial arts','professional sport','jazz music'],1],['Pat and Tim both love…',['music','concerts','golf','karate'],0]
);
tests.english.questions.splice(0,15,
['Choose the correct form: She ___ to university every day.',['go','goes','going','gone'],1],['Complete: I ___ my homework yesterday.',['finish','finished','have finish','am finishing'],1],['Choose the correct option: There ___ any milk in the fridge.',['isn’t','aren’t','don’t','doesn’t'],0],['Complete: He has lived in Almaty ___ five years.',['since','for','from','at'],1],['Choose the correct form: If I ___ you, I would study more.',['am','was','were','be'],2],['Choose the correct preposition: She is good ___ mathematics.',['at','in','on','for'],0],['Complete: This book is ___ than that one.',['interesting','more interesting','most interesting','interest'],1],['Choose the correct modal verb: You ___ wear a seatbelt.',['must','can to','should to','musts'],0],['Complete: By 2030, they ___ the project.',['will have completed','complete','completed','are completed'],0],['Choose the correct passive form: They build houses here.',['Houses are built here.','Houses build here.','Houses were build here.','Houses are building here.'],0],['Complete: I enjoy ___ English books.',['read','reading','to readed','reads'],1],['Choose the correct question:',['Where do you live?','Where you live?','Where are live you?','Where live you?'],0],['Complete: Neither my brother nor my sister ___ at home.',['are','is','be','were'],1],['Choose the correct connector: ___ he was tired, he continued working.',['Although','Because','So','Therefore'],0],['Complete: She asked me where I ___.',['lived','live','am living','will live'],0]
);
tests.english.questions.push(
['Choose the correct article: It is ___ useful book.',['a','an','the','no article'],0],['Complete: We ___ dinner when the lights went out.',['were having','have','had','will have'],0],['Choose the correct word: There are ___ students in the room.',['much','many','little','less'],1],['Complete: I have never ___ to London.',['been','gone','went','being'],0],['Choose the correct form: He speaks English ___.',['fluent','fluently','fluency','more fluent'],1],['Choose the correct option: My bag is ___ than yours.',['heavy','heavier','heaviest','more heavy'],1],['Complete: You ___ smoke here.',['mustn’t','don’t have','can','should to'],0],['Choose the correct pronoun: This is the student ___ won the prize.',['who','which','where','when'],0],['Complete: She is interested ___ learning languages.',['in','on','at','to'],0],['Choose the correct form: If it rains, we ___ at home.',['will stay','would stay','stayed','stay'],0],['Choose the correct word: I need ___ umbrella today.',['an','a','the','some'],0],['Complete: He ___ already left when I arrived.',['had','has','was','did'],0],['Choose the correct verb: My parents ___ television every evening.',['watch','watches','watching','watched'],0],['Complete: I am looking forward to ___ you.',['seeing','see','saw','seen'],0],['Choose the correct sentence.',['She doesn’t like coffee.','She don’t like coffee.','She doesn’t likes coffee.','She not like coffee.'],0],['Complete: The test was ___ than I expected.',['easier','easy','easiest','more easy'],0],['Choose the correct quantifier: There is ___ water left.',['a little','a few','many','few'],0],['Complete: I wish I ___ more free time.',['had','have','will have','am having'],0],['Choose the correct word: The opposite of “borrow” is…',['lend','take','keep','lose'],0],['Complete: They have known each other ___ school.',['since','for','during','from'],0],['Choose the correct form: The letter ___ yesterday.',['was sent','sent','is sent','has sent'],0],['Complete: She told me that she ___ busy.',['was','is','will be','has'],0],['Choose the correct word: He is the ___ student in the class.',['best','better','good','well'],0],['Complete: We ___ lunch at 1 p.m. every day.',['have','are having','had','will have'],0],['Choose the correct preposition: The meeting starts ___ Monday.',['on','in','at','by'],0],['Complete: I can’t find my keys. I ___ them.',['may have lost','must lose','am lose','have losing'],0],['Choose the correct form: She ___ in this company since 2022.',['has worked','works','worked','is work'],0],['Complete: There is not ___ information in the report.',['enough','many','few','several'],0],['Choose the correct word: A person who writes books is an…',['author','actor','artist','engineer'],0],['Complete: Unless you hurry, you ___ the bus.',['will miss','would miss','missed','are miss'],0]
);
tests.english.questions.push(
['Complete: The students ___ for the exam at the moment.',['are preparing','prepare','prepared','have prepare'],0],['Choose the correct form: I ___ my friend tomorrow.',['am meeting','met','have met','meet yesterday'],0],['Complete: This is ___ university in our city.',['the oldest','older','oldest','the older'],0],['Choose the correct word: You ___ to see a doctor.',['should','shoulds','are should','should to'],0],['Complete: If she had studied, she ___ the exam.',['would have passed','will pass','passes','would pass'],0],['Choose the correct form: The documents need ___.',['checking','to check','checked by they','check'],0],['Complete: I don’t know ___ he will come.',['whether','what','which','whose'],0],['Choose the correct noun: Her ___ was very clear.',['explanation','explain','explainingly','explained'],0],['Complete: No sooner had we arrived ___ it began to rain.',['than','when','then','that'],0],['Choose the correct phrase:',['depend on','depend of','depend at','depend for'],0]
);
tests.readiness.questions.push(
['Все исследователи читают источники. Дана читает источники. Какой вывод верен?',['Дана точно исследователь','Дана может не быть исследователем','Никто не читает источники','Источники не нужны'],1],['Продолжите ряд: 1, 4, 9, 16, …',['25','20','24','32'],0],['Какой вопрос проверяет достоверность источника?',['Кто автор и на какие данные он опирается?','Красивый ли заголовок?','Сколько страниц в тексте?','Нравится ли вывод?'],0],['Если утверждение верно для трёх примеров, значит…',['его нельзя без проверки считать общим правилом','оно всегда верно','оно является законом','доказательства не нужны'],0],['Найдите лишнее: доказательство, тезис, аргумент, пароль.',['Пароль','Тезис','Аргумент','Доказательство'],0],['Продолжите ряд: 81, 27, 9, 3, …',['1','2','0','6'],0],['Что необходимо отличать при анализе новости?',['Факты и интерпретации','Шрифт и цвет','Длину и ширину','Время и дату'],0],['Если все A относятся к B, а X относится к A, то…',['X относится к B','B относится к X','X не относится к B','вывод невозможен'],0],['Какой приём помогает увидеть закономерность в таблице?',['Сравнить значения и изменения','Выбрать первое число','Игнорировать заголовки','Переписать таблицу'],0],['Что является сильным аргументом?',['Проверяемый факт из надёжного источника','Личное предположение','Громкое утверждение','Повторение тезиса'],0]
);
tests.profile.questions.push(
['Как в Python обозначается список?',['[]','{}','()','<>'],0],['Что делает оператор continue?',['Переходит к следующей итерации цикла','Завершает программу','Удаляет массив','Создаёт класс'],0],['Какой тип в Java хранит логическое значение?',['boolean','integer','string','double'],0],['Для чего используется переменная-счётчик?',['Для подсчёта повторений','Для шифрования файла','Для создания сети','Для удаления данных'],0],['Как называется ошибка выполнения программы?',['Runtime error','Comment','Variable','Loop'],0],['Что такое атака перебором пароля?',['Подбор множества вариантов пароля','Резервное копирование','Архивация данных','Обновление системы'],0],['Какой принцип требует минимальных прав доступа?',['Least privilege','Open access','Public key','Full control'],0],['Что защищает VPN при передаче данных?',['Создаёт защищённый туннель','Удаляет вирусы','Заменяет пароль','Ускоряет процессор'],0],['Какой метод подтверждает подлинность отправителя сообщения?',['Цифровая подпись','Удаление файла','Сжатие данных','Сортировка'],0],['Что нужно делать с резервными копиями?',['Регулярно проверять возможность восстановления','Хранить только на одном устройстве','Никогда не обновлять','Открывать всем пользователям'],0]
);
tests.english.questions.push(
['Complete: I ___ never seen this film before.',['have','has','had','am'],0],['Choose the correct word: He speaks very ___.',['clearly','clear','clearness','cleared'],0],['Complete: The lecture ___ at 9 a.m. tomorrow.',['starts','start','is start','started'],0],['Choose the correct form: She asked me ___ I was ready.',['if','that','what','which'],0],['Complete: This exercise is not ___ difficult.',['too','enough','many','such'],0],['Choose the correct phrase:',['make a decision','do a decision','take a decision up','create a deciding'],0],['Complete: They ___ the report before the deadline.',['had finished','have finish','were finish','finishes'],0],['Choose the correct relative pronoun: The book ___ I bought is useful.',['that','who','where','when'],0],['Complete: He is used to ___ early.',['getting up','get up','got up','gets up'],0],['Choose the correct word: We need to ___ attention to details.',['pay','do','make','take'],0]
);
tests.readiness.questions.push(
['Продолжите ряд: 5, 10, 20, 40, …',['80','60','70','90'],0],['Что нужно сделать, если два источника противоречат друг другу?',['Сравнить их основания и надёжность','Выбрать первый','Не читать оба','Сделать случайный вывод'],0],['Все книги в этой коробке новые. Эта книга из коробки. Какой вывод?',['Эта книга новая','Книга старая','Книг нет','Вывод невозможен'],0],['Какое утверждение является фактом?',['Вода замерзает при 0°C при нормальном давлении','Этот фильм лучший','Задание очень сложное','Книга интересная'],0],['Продолжите ряд: 2, 3, 5, 8, 12, …',['17','15','18','20'],0],['Для чего нужны критерии оценки аргумента?',['Чтобы проверять его силу и обоснованность','Чтобы сделать текст длиннее','Чтобы заменить факты','Чтобы не читать источник'],0],['Какой вывод следует из диаграммы корректнее всего?',['Тот, который опирается на подписи и значения','Самый эмоциональный','Самый короткий','Тот, что нравится автору'],0],['Если причина не доказана, связь между событиями следует назвать…',['предположением','фактом','законом','опровержением'],0],['Какой признак характеризует аналитическое мышление?',['Разделение задачи на части и поиск связей','Запоминание без анализа','Отказ от данных','Повторение мнения'],0],['Что помогает проверить вывод?',['Сопоставление его с исходными данными','Изменение шрифта','Выбор другой темы','Повторение вывода'],0]
);
tests.profile.questions.push(
['Что делает функция input() в Python?',['Получает ввод пользователя','Выводит текст','Удаляет переменную','Сортирует список'],0],['Как в C++ обозначается блок кода?',['Фигурными скобками','Квадратными скобками','Кавычками','Знаком #'],0],['Какой оператор сравнения означает «не равно»?',['!=','==','<=','=>'],0],['Что хранит переменная типа float?',['Число с дробной частью','Только текст','Логическое значение','Массив'],0],['Что такое цикл с предусловием?',['while','do while','switch','if'],0],['Как называется программа, перехватывающая нажатия клавиш?',['Keylogger','Firewall','Backup','Browser'],0],['Какой вид атаки перегружает сервер запросами?',['DDoS','Phishing','Backup','Hashing'],0],['Для чего используют TLS-сертификат?',['Для подтверждения подлинности сайта и защиты соединения','Для удаления вирусов','Для сортировки данных','Для создания архива'],0],['Что такое уязвимость нулевого дня?',['Неисправленная неизвестная или новая уязвимость','Пароль из нуля','Нулевой размер файла','Резервная копия'],0],['Что помогает защититься от социальной инженерии?',['Проверка запросов и обучение пользователей','Передача пароля по телефону','Отключение обновлений','Использование одного пароля'],0]
);
function fillQuestionBanks(){
  let subjects=['I','She','He','They','We','My friend','The student','Our teacher','The researchers','The team'];
  let verbs=['work','talk','walk','help','learn','play','visit','clean','cook','open'];
  for(let n=0;tests.english.questions.length<200;n++){let s=subjects[n%subjects.length],v=verbs[n%verbs.length],time=n%3;if(time===0)tests.english.questions.push([`Choose the correct form: ${s} ___ English every day.`,[v,`${v}s`,`${v}ing`,`${v}ed`],s==='I'||s==='They'||s==='We'?0:1]);else if(time===1)tests.english.questions.push([`Complete: ${s} ___ ${v}ing when the lesson started.`,['was', 'were','is','has'],s==='I'||s==='He'||s==='She'||s==='My friend'||s==='Our teacher'||s==='The student'||s==='The team'?0:1]);else tests.english.questions.push([`Complete: ${s} ___ already ${v}ed the assignment.`,['have','has','had','are'],s==='I'||s==='They'||s==='We'||s==='The researchers'?0:1])}
  for(let n=0;tests.readiness.questions.length<200;n++){let a=2+n,b=3+(n%7),c=a+b,d=c+b;tests.readiness.questions.push([`Продолжите числовой ряд: ${a}, ${c}, ${d}, …`,[String(d+b),String(d+a),String(c+b+1),String(d+2*b)],0])}
  let langs=['Python','C++','Java'],structures=['стек','очередь','массив','список'],threats=['фишинг','DDoS-атака','троян','кейлоггер'],security=['конфиденциальность','целостность','доступность','аутентификация'];
  for(let n=0;tests.profile.questions.length<200;n++){if(n%2===0){let lang=langs[n%langs.length],item=structures[n%structures.length];tests.profile.questions.push([`Какое утверждение о структуре «${item}» верно при программировании на ${lang}?`,item==='стек'?['Элементы извлекаются последними добавленными','Элементы извлекаются первыми добавленными','Структура хранит только строки','Структура не содержит данных']:item==='очередь'?['Элементы извлекаются первыми добавленными','Элементы извлекаются последними добавленными','Она не поддерживает добавление','Она всегда отсортирована']:['Она хранит набор элементов','Она служит только для шифрования','Она удаляет программу','Она не имеет размера'],0])}else{let threat=threats[n%threats.length],goal=security[n%security.length];tests.profile.questions.push([`Какой термин ИБ связан с понятием «${threat}»?`,[threat,goal,'Компилятор','Сортировка'],0])}}
}
fillQuestionBanks();
function extendQuestionBanks(){
  let englishSubjects=['I','She','He','They','We','My friend','The student','Our teacher','The researchers','The team'];
  let englishVerbs=['work','talk','walk','help','learn','play','visit','clean','cook','open'];
  for(let n=0;tests.english.questions.length<500;n++){let s=englishSubjects[n%englishSubjects.length],v=englishVerbs[n%englishVerbs.length],correct=s==='I'||s==='They'||s==='We'?0:1;tests.english.questions.push([`Choose the correct form: ${s} ___ ${v} every day.`,[v,`${v}s`,`${v}ing`,`${v}ed`],correct])}
  for(let n=0;tests.readiness.questions.length<500;n++){let start=n+11,stepSize=(n%9)+2,second=start+stepSize,third=second+stepSize;tests.readiness.questions.push([`Продолжите ряд: ${start}, ${second}, ${third}, …`,[String(third+stepSize),String(third+start),String(third+stepSize+1),String(third+2*stepSize)],0])}
  let concepts=['стек','очередь','массив','цикл'],risks=['фишинг','DDoS-атака','троян','кейлоггер'];
  for(let n=0;tests.profile.questions.length<500;n++){if(n%2===0){let c=concepts[n%concepts.length];tests.profile.questions.push([`Какое понятие программирования описывается как «${c}»?`,[c,'Шифрование','Вредоносное ПО','Сетевой протокол'],0])}else{let r=risks[n%risks.length];tests.profile.questions.push([`Какой термин информационной безопасности соответствует описанию «${r}»?`,[r,'Компиляция','Сортировка','Массив'],0])}}
}
extendQuestionBanks();
const curatedEnglish=[
['Choose the correct option: I ___ for a reply for several weeks and still have not received an answer.',['have been waiting','wait','was waiting','am wait'],0,'Present perfect continuous','The action began in the past and continues up to the present.'],
['Complete: This is ___ room in our house.',['the smallest','smallest','more small','the most small'],0,'Adjectives','Superlatives normally use “the” before the adjective.'],
['Choose the correct form: I ___ when my friend called.',['was sleeping','slept','am sleeping','had sleep'],0,'Past continuous','A continuing past action interrupted by another action uses Past Continuous.'],
['Complete: Scientists ___ everything about the universe.',['do not understand','are not understanding','do not understands','not understand'],0,'Present simple','“Understand” is normally a stative verb and uses Present Simple.'],
['Choose the correct option: Galileo is supposed ___ the telescope.',['to have invented','have invented','inventing','to inventing'],0,'Infinitive forms','“Is supposed to have + past participle” refers to a past action.'],
['Complete: Most days the shop ___ at 10 p.m.',['closes','close','closing','will close'],0,'Present simple','Use Present Simple for a regular timetable or schedule.'],
['Choose the correct word: Almaty is the ___ point I have gone so far.',['farthest','father','further','more far'],0,'Irregular adjectives','“Far” has the superlative form “farthest/furthest”.'],
['Complete: It ___ be cold tomorrow.',['may','ought','has','did'],0,'Modal verbs','“May” expresses possibility in the future.'],
['Choose the correct preposition: I cannot come to the party ___ Saturday.',['on','in','at','under'],0,'Prepositions','Use “on” with days of the week.'],
['Complete: I stopped ___ my book and went to bed.',['reading','read','to readed','will read'],0,'Gerunds','“Stop doing” means to discontinue an activity.']
];
const curatedTgo=[
['Все магистранты пишут исследование. Айдана — магистрант. Какой вывод следует?',['Айдана пишет исследование','Айдана не пишет исследование','Только Айдана пишет исследование','Вывод невозможен'],0,'Критическое мышление','Это дедуктивный вывод: свойство общего класса относится к его элементу.'],
['Продолжите ряд: 3, 6, 12, 24, …',['48','36','42','54'],0,'Аналитическое мышление','Каждый следующий элемент в два раза больше предыдущего.'],
['Как проверить, что аргумент надёжен?',['Проверить источник и доказательства','Выбрать самый уверенный тон','Согласиться с большинством','Игнорировать контраргументы'],0,'Критическое мышление','Надёжный аргумент опирается на проверяемые основания.'],
['Продолжите ряд: 1, 4, 9, 16, …',['25','20','24','30'],0,'Аналитическое мышление','Это квадраты последовательных натуральных чисел: 1², 2², 3², 4², 5².'],
['Что отличает факт от мнения?',['Факт можно проверить данными','Факт всегда нравится читателю','Мнение длиннее','Мнение содержит число'],0,'Критическое мышление','Факт можно подтвердить наблюдением, документом или исследованием.'],
['Если все A относятся к B, а X относится к A, то…',['X относится к B','B относится к X','X не относится к B','вывод невозможен'],0,'Критическое мышление','Это силлогизм: принадлежность передаётся от частного к общему классу.'],
['Продолжите ряд: 81, 27, 9, 3, …',['1','2','6','0'],0,'Аналитическое мышление','Каждый элемент делится на 3.'],
['Что следует делать с противоречивой информацией?',['Сравнить источники и основания','Выбрать удобную версию','Игнорировать оба текста','Сразу делать вывод'],0,'Критическое мышление','Сначала нужно оценить достоверность и доказательность каждого источника.'],
['Продолжите ряд: 2, 5, 10, 17, …',['26','22','24','30'],0,'Аналитическое мышление','Прибавляются нечётные числа: +3, +5, +7, +9.'],
['Что такое контраргумент?',['Обоснованное возражение против тезиса','Повтор тезиса','Название текста','Эмоциональная оценка'],0,'Критическое мышление','Контраргумент проверяет тезис через альтернативную позицию.']
];
const curatedProfile=[
['Какой алгоритм сортировки имеет худшую временную сложность O(n²)?',['Быстрая сортировка','Сортировка слиянием','Пузырьковая сортировка','Бинарный поиск'],2,'Программирование','Пузырьковая сортировка в худшем случае сравнивает пары элементов квадратичное число раз.'],
['Какая структура данных хранит элементы в виде узлов с родителями и потомками?',['Массив','Стек','Очередь','Дерево'],3,'Программирование','Иерархическая структура с родительскими и дочерними узлами — это дерево.'],
['Какой алгоритм ищет кратчайший путь во взвешенном графе с неотрицательными весами?',['Поиск в глубину','Алгоритм Дейкстры','Пузырьковая сортировка','Бинарный поиск'],1,'Программирование','Алгоритм Дейкстры находит кратчайшие пути от одной вершины при неотрицательных весах.'],
['Какой тип Python хранит пары «ключ—значение»?',['list','tuple','dict','set'],2,'Программирование','Словарь dict сопоставляет уникальные ключи со значениями.'],
['Какой модификатор Java делает метод доступным только внутри класса?',['public','private','protected','static'],1,'Программирование','Модификатор private ограничивает доступ текущим классом.'],
['Какой принцип относится к CIA-триаде?',['Конфиденциальность','Производительность','Масштабируемость','Совместимость'],0,'Информационная безопасность','CIA-триада включает конфиденциальность, целостность и доступность.'],
['Какой алгоритм создаёт криптографический хеш?',['AES','RSA','SHA-256','DES'],2,'Информационная безопасность','SHA-256 — хеш-функция; AES и RSA применяются для шифрования.'],
['Какой протокол предназначен для безопасной передачи файлов?',['FTP','SFTP','HTTP','Telnet'],1,'Информационная безопасность','SFTP передаёт файлы через защищённый SSH-канал.'],
['Что является примером симметричного шифрования?',['RSA','AES','SHA-256','ECC'],1,'Информационная безопасность','AES использует один общий секретный ключ для шифрования и расшифрования.'],
['Как называется проверка прав доступа пользователя к ресурсу?',['Аутентификация','Авторизация','Хеширование','Токенизация'],1,'Информационная безопасность','Аутентификация подтверждает личность, а авторизация проверяет разрешения.']
];
curatedProfile.push(
['Какой подход помогает подсчитать количество уникальных элементов списка Python?',['Использование множества set','Пузырьковая сортировка','Рекурсивный перебор без проверки','Линейный поиск каждого элемента без хранения результата'],0,'Программирование','Множество set хранит только уникальные значения.'],
['Какой оператор C выделяет память под массив?',['malloc()','free()','sizeof','delete'],0,'Программирование','Функция malloc выделяет блок динамической памяти.'],
['Какой способ подходит для проверки палиндрома?',['Сравнивать символы с начала и конца строки','Сортировать символы','Искать максимальное число','Удалять строку'],0,'Программирование','У палиндрома симметричные символы совпадают при сравнении с двух концов.'],
['Как найти максимальный элемент в неотсортированном массиве?',['Выполнить линейный перебор','Применить бинарный поиск','Использовать поиск в глубину','Сравнить только первый и последний элементы'],0,'Программирование','Нужно пройти по всем элементам и поддерживать текущий максимум.'],
['Какая структура подходит для проверки сбалансированности скобок?',['Стек','Очередь','Дерево поиска','Массив без индексов'],0,'Программирование','Стек хранит открывающие скобки в порядке LIFO.'],
['Какая мера помогает предотвратить переполнение буфера?',['Проверка границ входных данных','Разрешение неограниченного ввода','Отключение обработки ошибок','Использование устаревших библиотек'],0,'Информационная безопасность','Проверка длины и безопасные библиотеки предотвращают выход за границы буфера.'],
['Что помогает предотвратить XSS-атаки в веб-приложении?',['Экранирование пользовательского ввода','Разрешение всех скриптов','Отключение серверной валидации','Использование HTTP вместо HTTPS'],0,'Информационная безопасность','Непроверенный ввод нужно экранировать и валидировать до вывода в HTML.'],
['Какая мера защищает данные базы данных?',['Ограничение доступа по ролям','Открытие всех портов','Стандартные пароли','Отключение журналов событий'],0,'Информационная безопасность','Ролевая модель выдаёт пользователю только необходимые права.'],
['Что помогает расследовать источник подозрительного сетевого трафика?',['Анализ сетевых журналов','Удаление всех данных','Игнорирование трафика','Открытие всех портов'],0,'Информационная безопасность','Логи и мониторинг позволяют установить источник и характер активности.'],
['Какое действие помогает избежать фишинга?',['Проверять отправителя и адрес ссылки','Переходить по всем ссылкам','Отправлять пароль в ответ','Отключать фильтры спама'],0,'Информационная безопасность','Фишинговые письма часто маскируют адрес отправителя и URL ссылки.']
);
tests.english.questions=[...curatedEnglish,...tests.english.questions].slice(0,500);
tests.readiness.questions=[...curatedTgo,...tests.readiness.questions].slice(0,500);
tests.profile.questions=[...curatedProfile,...tests.profile.questions].slice(0,500);
tests.profile.questions.unshift(
['Количество сравнений, выполняемых быстрой сортировкой для массива размера N в худшем случае?',['N/4','N²/2','N/3','N/2'],1,'Программирование','В худшем случае quicksort имеет квадратичную сложность; число сравнений пропорционально N²/2.'],
['Какой стандартный заголовок C позволяет учитывать локаль программы?',['<local.h>','<stdlib.h>','<locale.h>','<loctime.h>'],2,'Программирование','Заголовок <locale.h> содержит средства для работы с локалью.'],
['Какая конструкция C++ выполняет множественный выбор по значению выражения?',['while','grade','square','for','switch'],4,'Программирование','Конструкция switch сопоставляет выражение с наборами значений case.'],
['Какие деревья содержат не более двух ссылок на потомков у каждого узла?',['Кустистые','Ветвящиеся','Корневые','Двоичные','Листовые'],3,'Программирование','В двоичном дереве у каждого узла может быть левый и правый потомок.'],
['Как называется математическая структура из вершин и рёбер, соединяющих эти вершины?',['Куст','Маршрут','Граф','Шаблон','Схема'],2,'Программирование','Граф состоит из множества вершин и множества рёбер между ними.']
);
tests.profile.questions=tests.profile.questions.slice(0,500);
tests.english.questions.forEach(q=>{if(String(q[0]).includes('The researchers')){if(String(q[0]).includes('every day'))q[2]=0;if(String(q[0]).includes('when the lesson started'))q[2]=1}});
function sectionName(){if(active.id==='english')return 'Лексико-грамматический тест';if(active.id==='readiness')return step<15?'Критическое мышление':'Аналитическое мышление';return step<20?'Алгоритмические языки программирования':'Основы информационной безопасности'}
const modal=document.querySelector('#test-modal'), app=document.querySelector('#test-app');let active,step,answers;
document.querySelectorAll('[data-test]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.test,b.dataset.mode==='learn')));document.querySelector('.modal-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}function shuffle(list){return [...list].sort(()=>Math.random()-.5)}function start(id,learn=false){let limit=id==='english'?50:id==='readiness'?30:40;active={...tests[id],id,questions:shuffle(tests[id].questions).slice(0,limit),learn};step=0;answers=[];modal.classList.add('open');modal.setAttribute('aria-hidden','false');render()}
function render(){let q=active.questions[step],chosen=answers[step],review=active.learn&&chosen!==undefined;app.innerHTML=`<div class="quiz-top"><div><p class="eyebrow">${sectionName()}${active.learn?' · РЕЖИМ ТРЕНИРОВКИ':''}</p><h2>${active.title}</h2></div><span class="quiz-counter">${step+1} / ${active.questions.length}</span></div><div class="progress"><i style="width:${(step+1)/active.questions.length*100}%"></i></div><div class="question">${step+1}. ${q[0]}</div><div class="answers">${q[1].map((a,i)=>`<button class="answer ${chosen===i?'selected':''} ${review&&i===q[2]?'correct':''} ${review&&chosen===i&&i!==q[2]?'incorrect':''}" data-a="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('')}</div>${review?`<p class="answer-feedback">${chosen===q[2]?'Верно!':'Правильный ответ: '+String.fromCharCode(65+q[2])+'. '+q[1][q[2]]}</p>`:''}<div class="quiz-actions"><button id="prev" ${step?'':'disabled'}>← Назад</button><button id="next" ${chosen===undefined?'disabled':''}>${step===active.questions.length-1?'Завершить':'Далее →'}</button></div>`;app.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(!review){answers[step]=+b.dataset.a;render()}});app.querySelector('#prev').onclick=()=>{step--;render()};app.querySelector('#next').onclick=()=>{if(step<active.questions.length-1){step++;render()}else result()}}
function result(){const score=answers.reduce((s,a,i)=>s+(a===active.questions[i][2]),0),pct=Math.round(score/active.questions.length*100),message=pct>=80?'Отличный результат — вы уверенно владеете материалом.':pct>=50?'Хорошая основа. Повторите темы, где возникли сложности.':'Продолжайте подготовку: библиотека материалов уже ждёт вас.';app.innerHTML=`<div class="result"><p class="eyebrow">РЕЗУЛЬТАТ ГОТОВ</p><div class="score">${score}/${active.questions.length}</div><h2>${pct}% правильных ответов</h2><p>${message}</p><button onclick="start('${active.id}',${active.learn})">Пройти ещё раз</button></div>`}

var timerHandle=null,timeLeft=0;
function testSeconds(id){return id==='english'?3300:id==='readiness'?2100:2700}
function topicOf(q){if(q[3])return q[3];let text=String(q[0]).toLowerCase();if(active.id==='english')return 'Грамматика и лексика';if(active.id==='readiness')return /\d/.test(text)?'Аналитическое мышление':'Критическое мышление';return /шифр|уязв|атак|фиш|троян|кцд|доступ|парол|иб|tls|ddos|безопас/.test(text)?'Информационная безопасность':'Программирование'}
function explanation(q){if(q[4])return q[4];let topic=topicOf(q);if(topic==='Грамматика и лексика')return 'Проверьте форму глагола, время и согласование с подлежащим.';if(topic==='Аналитическое мышление')return 'Найдите правило изменения чисел и примените его к следующему элементу.';if(topic==='Критическое мышление')return 'Опирайтесь только на факты и логически следующие выводы.';if(topic==='Информационная безопасность')return 'Соотнесите угрозу или принцип защиты с его точным определением.';return 'Определите назначение конструкции, структуры данных или оператора.'}
function persist(){try{if(active)localStorage.setItem('magisterium-attempt',JSON.stringify({active,step,answers,timeLeft}))}catch(e){}}
function clearPersist(){try{localStorage.removeItem('magisterium-attempt')}catch(e){}}
function startTimer(){clearInterval(timerHandle);timerHandle=setInterval(()=>{timeLeft--;persist();let t=document.querySelector('#timer');if(t)t.textContent=`⏱ ${Math.floor(timeLeft/60)}:${String(timeLeft%60).padStart(2,'0')}`;if(timeLeft<=0){clearInterval(timerHandle);result()}},1000)}
function close(){clearInterval(timerHandle);persist();modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function shuffle(list){return [...list].sort(()=>Math.random()-.5)}
function start(id,learn=false,questions=null){let saved;try{saved=JSON.parse(localStorage.getItem('magisterium-attempt'))}catch(e){}if(!questions&&saved&&saved.active&&saved.active.id===id&&confirm('Продолжить сохранённую попытку?')){active=saved.active;step=saved.step;answers=saved.answers;timeLeft=saved.timeLeft}else{let limit=id==='english'?50:id==='readiness'?30:40,qualityLimit={english:90,readiness:60,profile:70},bank=tests[id].questions.slice(0,qualityLimit[id]);active={...tests[id],id,questions:questions||shuffle(bank).slice(0,limit),learn};step=0;answers=[];timeLeft=testSeconds(id);persist()}modal.classList.add('open');modal.setAttribute('aria-hidden','false');startTimer();render()}
function render(){let q=active.questions[step],chosen=answers[step],review=active.learn&&chosen!==undefined;app.innerHTML=`<div class="quiz-top"><div><p class="eyebrow">${topicOf(q)}${active.learn?' · ТРЕНИРОВКА':''}</p><h2>${active.title}</h2></div><span class="quiz-counter" id="timer">⏱ ${Math.floor(timeLeft/60)}:${String(timeLeft%60).padStart(2,'0')}</span></div><div class="progress"><i style="width:${(step+1)/active.questions.length*100}%"></i></div><div class="question">${step+1}. ${q[0]}</div><div class="answers">${q[1].map((a,i)=>`<button class="answer ${chosen===i?'selected':''} ${review&&i===q[2]?'correct':''} ${review&&chosen===i&&i!==q[2]?'incorrect':''}" data-a="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('')}</div>${review?`<p class="answer-feedback">${chosen===q[2]?'Верно!':'Правильный ответ: '+String.fromCharCode(65+q[2])+'. '+q[1][q[2]]}<br><small>${explanation(q)}</small></p>`:''}<div class="quiz-actions"><button id="prev" ${step?'':'disabled'}>← Назад</button><button id="next" ${chosen===undefined?'disabled':''}>${step===active.questions.length-1?'Завершить':'Далее →'}</button></div>`;app.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{if(!review){answers[step]=+b.dataset.a;persist();render()}});app.querySelector('#prev').onclick=()=>{step--;persist();render()};app.querySelector('#next').onclick=()=>{if(step<active.questions.length-1){step++;persist();render()}else result()}}
function repeatMistakes(){let wrong=active.questions.filter((q,i)=>answers[i]!==q[2]);if(!wrong.length){alert('Ошибок нет — отличная работа!');return}clearPersist();start(active.id,true,wrong)}
function result(){clearInterval(timerHandle);clearPersist();let score=answers.reduce((s,a,i)=>s+(a===active.questions[i][2]),0),pct=Math.round(score/active.questions.length*100),stats={};active.questions.forEach((q,i)=>{let t=topicOf(q);stats[t]??={ok:0,total:0};stats[t].total++;if(answers[i]===q[2])stats[t].ok++});let rows=Object.entries(stats).map(([t,v])=>`<li><span>${t}</span><b>${v.ok}/${v.total}</b></li>`).join('');let errors=active.questions.map((q,i)=>answers[i]===q[2]?'':`<li>${i+1}. ${q[0]} <b>→ ${q[1][q[2]]}</b></li>`).filter(Boolean).join('')||'<li>Нет ошибок.</li>';app.innerHTML=`<div class="result"><p class="eyebrow">РЕЗУЛЬТАТ ГОТОВ</p><div class="score">${score}/${active.questions.length}</div><h2>${pct}% правильных ответов</h2><div class="result-breakdown"><b>Результаты по темам</b><ul>${rows}</ul></div><details class="mistakes"><summary>Посмотреть ошибки (${active.questions.length-score})</summary><ol>${errors}</ol></details><button onclick="repeatMistakes()">Повторить ошибки</button><button onclick="start('${active.id}',${active.learn})">Новая попытка</button></div>`}
